# Generated by Django 5.0.3 on 2024-10-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='APIModel',
        ),
    ]
